on:
  push:
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: deps
      run: pip install ruff
    - uses: actions/checkout@v3
    - name: lint
      run: ruff upload.py
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: upload
      uses: ./
      with:
        meta-path: test/meta.json
        do-upload: false
        cli-config-secret: ${{ secrets.cli_config }}
