on:
  push:
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: upload
      uses: viamrobotics/upload-module@main
      with:
        meta-path: test/meta.json
        org-id: ${{ secrets.test_org_id }}
        do-upload: false
        cli-config-secret: ${{ secrets.cli_config }}
